version: "3"
services:
  mango-server:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://root:password@db:5432/mango?schema=public
    volumes:
      - ./src:/app/src
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mango-network

  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mango
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d mango"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mango-network

volumes:
  postgres-data: {}

networks:
  mango-network:
    driver: bridge
